# proto-file: protos/symfs.proto
# proto-name: everchanging.symfs.Config

# Relative paths are generally not supported. This is created just as an
# example; the generated SymFs has broken links as a result.
path: "./example/views"
source_paths: "./example/media"

metadata_file_patterns: "^(info|metadata)\.(textproto|pb\.txt)$"

group_by {
  name: "cast"
  field: "casts"
  max_repeated_group: 1
}
