
name: Integrate

on:
  push:
    branches: [ master ]

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: bazelbuild/setup-bazelisk@v1

      - uses: actions/checkout@v2

      - run: bazel build :symfs.par

      - run: bazel test --test_output=all :all

