
name: Integrate

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    container:
      image: implementing/builder:latest
      volumes:
        - /bazel/cache/symfs:/mnt/cache
    steps:
      - uses: actions/checkout@v4

      - run: bazel test --test_output=all :all

      - run: bazel build :symfs_zip

  # Ensures Dockerfile continues to build.
  integrate-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          push: false

  # Ensures builder.bash can build and test SymFs.
  integrate-builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: ./builder.bash test --test_output=all :all

      - run: ./builder.bash build :all
