name: Release

on:
  schedule:
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ steps.metadata.outputs.should_release }}
      release_name: ${{ steps.metadata.outputs.release_name }}
    steps:
      - uses: actions/checkout@v2

      - name: Generate Release Metadata
        id: metadata
        run: |
          echo "::set-output name=release_name::symfs_$(date +'%Y%m%d')"
          # If release is auto and no changes within last month, then skip.
          if [[ '${{ github.event_name }}' == 'schedule' && \
                -z "$(git rev-list --after='1 month' '${{ github.sha }}')" ]]; then
            echo '::set-output name=should_release::no'
          else
            echo '::set-output name=should_release::yes'
          fi

  release:
    needs: metadata
    runs-on: ubuntu-latest
    container:
      image: implementing/builder:latest
      volumes:
        - /bazel/cache/symfs:/mnt/cache
    if: ${{ needs.metadata.outputs.should_release == 'yes' }}
    steps:
      - uses: actions/checkout@v2

      - run: bazel test -c opt --test_output=all :all

      - run: bazel build -c opt :symfs_zip

      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'bazel-bin/symfs.zip,install/systemd/*'
          body: ""
          omitBody: true
          omitBodyDuringUpdate: true
          tag: ${{ needs.metadata.outputs.release_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: metadata
    runs-on: ubuntu-latest
    if: ${{ needs.metadata.outputs.should_release == 'yes' }}
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            implementing/symfs:latest
            implementing/symfs:${{ needs.metadata.outputs.release_name }}
            ghcr.io/directed-graph/symfs:latest
            ghcr.io/directed-graph/symfs:${{ needs.metadata.outputs.release_name }}
